# Generated by Django 3.1.7 on 2021-04-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='desc',
            field=models.CharField(max_length=400),
        ),
    ]
